### ISSUE TITLE
Generalized response

### ISSUE THREAD

**Issue by sander-blip** [PARCISZEWSKI/HCI_SKILL_REPO#13]
Robot: "How can I help you today?"
User: "Don't know."
Robot: "Ok, perfect let me ask you some questions to help you find it!"

So it doesn't really matter what you respond with it will automatically help you.

**Comment by PARCISZEWSKI** [comment]
This should already be implemented if I'm not incorrect, after the bot ask you how it can help you it should proceed no matter what the user responds with
